name: cpp-cmake-mingw-prebuilt-release-actions-workflow
on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
      - 'c*'

jobs:
  build:
    strategy:
      matrix:
        compiler:
        - {
            name: "x86_64-8.1.0-release-posix-seh-rt_v6-rev0",
            url: "https://github.com/dirkarnez/cpp-tools/raw/main/x86_64-8.1.0-release-posix-seh-rt_v6-rev0.7z"
          }
          
    runs-on: windows-latest
    env:
      libraryName: binutils-gdb
      installationPath: binutils-gdb-installation
      tagName: binutils-2_41-release
      mingwTargetZip: binutils-gdb-${{ github.ref_name }}-mingw64-x86_64-posix-seh-rev0-8.1.0.zip
    steps:
      - uses: actions/checkout@v3
      
      - run: git clone --recurse-submodules https://sourceware.org/git/binutils-gdb.git && cd binutils-gdb && git checkout ${{ env.tagName }}
          
      - name: Install MSYS2
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          install: make autoconf automake libtool autogen perl make texinfo flex bison
          
      - name: download compiler
        shell: cmd
        run: |
          curl ${{ matrix.compiler.url }} -L --output compiler &&^
          7z.exe x compiler
          
      - name: curl cmake-3.24.0-windows-x86_64.zip
        shell: cmd
        run: curl https://github.com/Kitware/CMake/releases/download/v3.24.0/cmake-3.24.0-windows-x86_64.zip -L --output cmake-3.24.0-windows-x86_64.zip && dir && 7z.exe x cmake-3.24.0-windows-x86_64.zip

      - shell: cmd
        run: |
          curl "https://github.com/dirkarnez/gmp-prebuilt/releases/download/v6.3.0/gmp-v6.3.0-mingw64-x86_64-posix-seh-rev0-8.1.0.zip" -L -O -J &&^
          7z.exe x gmp-v6.3.0-mingw64-x86_64-posix-seh-rev0-8.1.0.zip -o"gmp-v6.3.0-mingw64-x86_64-posix-seh-rev0-8.1.0"

      - shell: cmd
        run: |
          curl "https://github.com/dirkarnez/mpfr-prebuilt/releases/download/v4.2.0/mpfr-v4.2.0-mingw64-x86_64-posix-seh-rev0-8.1.0.zip" -L -O -J &&^
          7z.exe x mpfr-v4.2.0-mingw64-x86_64-posix-seh-rev0-8.1.0.zip -o"mpfr-v4.2.0-mingw64-x86_64-posix-seh-rev0-8.1.0"
          
      - name: set PATH, check mingw version, cmake generate, build and install
        shell: msys2 {0}
        run: |
            workspace=$(pwd) &&
            export PATH="$workspace/mingw64:$workspace/mingw64/bin:$workspace/msys64/usr/bin:/usr/bin" &&
            cd binutils-gdb && 
            gmp_root="$workspace/gmp-v6.3.0-mingw64-x86_64-posix-seh-rev0-8.1.0" &&
            mpfr_root="$workspace/mpfr-v4.2.0-mingw64-x86_64-posix-seh-rev0-8.1.0" &&
            g++ --version && 
            ./configure --help &&
            ./configure --with-gmp="$gmp_root" --with-mpfr="$mpfr_root" --prefix="$(pwd)/${{ env.installationPath }}" &&
            cat Makefile
            make VERBOSE=1 && make VERBOSE=1 install
            
      # - name: copy customized openssl-config.cmake
      #   shell: cmd
      #   run: xcopy /H /Y /C "openssl-config.cmake" "openssl\${{ env.installationPath }}"
        
      # - name: copy customized openssl-config.cmake
      #   shell: cmd
      #   run: xcopy /H /Y /C "openssl-config-version.cmake" "openssl\${{ env.installationPath }}"
        
      - name: Archive Release
        uses: thedoctor0/zip-release@master
        with:
          type: 'zip'
          directory: "binutils-gdb/${{ env.installationPath }}"
          filename: "${{ env.mingwTargetZip }}"
        
      - name: Release prebuilt
        uses: ncipollo/release-action@v1
        with:
          artifacts: "binutils-gdb/${{ env.installationPath }}/${{ env.mingwTargetZip }}"
          allowUpdates: true
          token: ${{ secrets.GITHUB_TOKEN }}
